name: vt_bin_new_3_

# rgb vs. low_dim: raw data are either rgb images or low_dim vectors. frames are aligned within each type.
# obs vs. action: obs data are used as policy input; action are used as labels for policy output.

# down_sample_steps: how many steps to skip in the raw data for the given usage
# horizon: how many steps to look ahead(action) or back(obs) after downsample for the given usage
sparse_obs_low_dim_down_sample_steps: 1
sparse_obs_low_dim_horizon: 3

sparse_action_down_sample_steps: 1
sparse_action_horizon: 32

# three items (matching bin1.yaml Genesis config)
item_pose_dim: [21]
item_pos_dim: [9]
item_rot_axis_angle_dim: [18]

# # two items
# item_pose_dim: [14]
# item_pos_dim: [6]
# item_rot_axis_angle_dim: [12]

shape_meta: &shape_meta
  id_list: [0]
  raw: # describes what exists in data
    js_fb_0:
      shape: [7]
      type: low_dim
    js_command_0:
      shape: [7]
      type: low_dim
    item_poses_0:
      shape: ${task.item_pose_dim}
      type: low_dim
    robot_time_stamps_0:
      shape: [1]
      type: timestamp
    item_time_stamps_0:
      shape: [1]
      type: timestamp

  obs: # describes observations loaded to memory 
    robot0_js:
      shape: [7]
      type: low_dim
    item_poses0_pos:
      shape: ${task.item_pos_dim}
      type: low_dim
    item_poses0_rot_axis_angle:
      shape: ${task.item_rot_axis_angle_dim}
      type: low_dim
      rotation_rep: rotation_6d
    robot_time_stamps_0:
      shape: [1]
      type: timestamp
    item_time_stamps_0:
      shape: [1]
      type: timestamp
  action: # describes actions loaded to memory, computed from robot command
    shape: [7] # js 
    rotation_rep: rotation_6d
  sample: # describes samples used in a batch
          # keys here must exist in obs/action above.
          # shape, type and rotation_rep are inherited from obs/action above.
    obs:
      sparse:
        robot0_js:
          horizon: ${task.sparse_obs_low_dim_horizon} # int
          down_sample_steps: ${task.sparse_obs_low_dim_down_sample_steps} # float
        item_poses0_pos:
          horizon: ${task.sparse_obs_low_dim_horizon} # int
          down_sample_steps: ${task.sparse_obs_low_dim_down_sample_steps} # float
        item_poses0_rot_axis_angle: # exists in data
          horizon: ${task.sparse_obs_low_dim_horizon} # int
          down_sample_steps: ${task.sparse_obs_low_dim_down_sample_steps} # float
    action:
      sparse:
        horizon: ${task.sparse_action_horizon}
        down_sample_steps: ${task.sparse_action_down_sample_steps} # int
    training_duration_per_sparse_query: 3500 # longer than the action horizon

task_name: &task_name
dataset_path: ${oc.env:PYRITE_DATASET_FOLDERS}/rrt_test_zarr
# dataset_path: ${oc.env:PYRITE_DATASET_FOLDERS}/bin_new_3_real_physics_zarr

env_runner: # used in workspace for computing metrics
  _target_: diffusion_policy.env_runner.real_pusht_image_runner.RealPushTImageRunner

dataset:
  _target_: diffusion_policy.dataset.virtual_target_dataset.VirtualTargetDataset
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  sparse_query_frequency_down_sample_steps: 1
  # cache_dir: null
  action_padding: True
  temporally_independent_normalization: False
  seed: 42
  val_ratio: 0.05
  normalize_wrench: True
  no_visual: True